### ISSUE TITLE
Light theme is illegible

### ISSUE THREAD

**Issue by kidonng** [dalance/procs#148]
procs version 0.11.6
Terminal: kitty 0.20.3

The light theme is illegible with both [light](https://github.com/folke/tokyonight.nvim/blob/main/extras/kitty_tokyonight_day.conf) and [dark](https://github.com/folke/tokyonight.nvim/blob/main/extras/kitty_tokyonight_storm.conf) terminal theme.

![image](https://user-images.githubusercontent.com/44045911/118759128-fdf77d80-b8a2-11eb-92b4-ebcebbbbfe53.png)
![image](https://user-images.githubusercontent.com/44045911/118759249-3ac37480-b8a3-11eb-84da-830b1944ab41.png)

**Comment by dalance** [comment]
By default, `color0` is used as the header and command color.
It is defined as "Black" in ANSI standard, but `color0` of kitty_tokyonight_day.conf is e9e9ed which is almost white.

You can adjust the color by config like below:

```toml
[style]
# header = "BrightWhite|Black" # this is default value
header = "BrightWhite|BrightWhite" # BrightWhite is the nearest color to black in kitty_tokyonight_day
```
