### ISSUE TITLE
Docker column is empty

### ISSUE THREAD

**Issue by Saduff** [dalance/procs#236]
I'm running procs as root, but the docker column is empty. My config:
```toml
[[columns]]
kind = "Docker"
style = "BrightGreen|Green"
numeric_search = false
nonnumeric_search = true
align = "Left"

[docker]
path = "unix:///var/run/docker.sock"
```

I can access the docker socket using curl:
```sh
curl --unix-socket /var/run/docker.sock http://localhost/containers/json
```
