### ISSUE TITLE
Possible to reorder columns?

### ISSUE THREAD

**Issue by dead10ck** [dalance/procs#43]
This wasn't clear to me from reading the README, but is it possible to reorder the columns? The default order has the process name off the edge of the screen, which makes it kind of difficult to use in a standard sized terminal.

**Comment by dalance** [comment]
The kind and order of columns can be customized by configuration file.
You can generate the sample file by `procs --config`.
The detailed information is below:

https://github.com/dalance/procs#configuration

For example, the column order becomes "Command" "Pid" "User" by the following config.

```toml
[[columns]]
kind = "Command"
style = "BrightWhite"
numeric_search = false
nonnumeric_search = true
align = "Left"

[[columns]]
kind = "Pid"
style = "BrightYellow"
numeric_search = true
nonnumeric_search = false
align = "Left"

[[columns]]
kind = "User"
style = "BrightGreen"
numeric_search = false
nonnumeric_search = true
align = "Left"
```

If "Command" column is too wide in your terminal size, you can specify the maximum width like below:

```toml
[[columns]]
kind = "Command"
style = "BrightWhite"
numeric_search = false
nonnumeric_search = true
align = "Left"
max_width = 50
```
